name: "build-test"
on:
  push:

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: 'Upload app to TestFlight'
        uses: ./
        with:
          app-path: 'path/to/application.ipa'
          issuer-id: test
          api-key-id: test
          api-private-key: test
          retry-attempts-on-timsseout: 10
